[tool.poetry]
name = "pythonproject"
version = "0.1.0"
description = ""
authors = ["Ivan Glushenkov <my_mail_Ivan@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
